"""users table

Revision ID: ea4bb5b0b511
Revises: 
Create Date: 2020-03-24 19:05:09.493722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea4bb5b0b511'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_administrator_group_name'), 'administrator', ['group_name'], unique=True)
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typeform_link', sa.String(length=256), nullable=True),
    sa.Column('reviews_per_app', sa.Integer(), nullable=True),
    sa.Column('semester', sa.String(length=64), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['administrator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_semester'), 'application', ['semester'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_semester'), table_name='application')
    op.drop_table('application')
    op.drop_index(op.f('ix_administrator_group_name'), table_name='administrator')
    op.drop_table('administrator')
    # ### end Alembic commands ###
